wandb_version: 1

dataset:
  desc: null
  value: imagenet
data_path:
  desc: null
  value: ''
model:
  desc: null
  value: tv_resnet18
model_config:
  desc: null
  value: ''
resume:
  desc: null
  value: ''
batch_size:
  desc: null
  value: 32
val_batch_size_multiplier:
  desc: null
  value: 1.0
auxiliary:
  desc: null
  value: false
auxiliary_weight:
  desc: null
  value: 0.4
smoothing:
  desc: null
  value: 0.0
opt:
  desc: null
  value: sgd
opt_eps:
  desc: null
  value: 1.0e-08
opt_no_filter:
  desc: null
  value: false
momentum:
  desc: null
  value: 0.9
sgd_no_nesterov:
  desc: null
  value: false
weight_decay:
  desc: null
  value: 0.0001
clip_grad_norm:
  desc: null
  value: false
clip_grad_max_norm:
  desc: null
  value: 5.0
amp:
  desc: null
  value: false
sched:
  desc: null
  value: step
decay_epochs:
  desc: null
  value: 30
lr:
  desc: null
  value: 0.1
warmup_lr:
  desc: null
  value: 0.2
min_lr:
  desc: null
  value: 1.0e-05
epochs:
  desc: null
  value: 100
warmup_epochs:
  desc: null
  value: 0
decay_rate:
  desc: null
  value: 0.1
decay_by_epoch:
  desc: null
  value: true
image_mean:
  desc: null
  value: null
image_std:
  desc: null
  value: null
interpolation:
  desc: null
  value: bilinear
color_jitter:
  desc: null
  value: 0.0
cutout_length:
  desc: null
  value: 0
aa:
  desc: null
  value: null
reprob:
  desc: null
  value: 0.0
remode:
  desc: null
  value: const
drop:
  desc: null
  value: 0.0
drop_path_rate:
  desc: null
  value: 0.0
drop_path_strategy:
  desc: null
  value: const
mixup:
  desc: null
  value: 0.0
cutmix:
  desc: null
  value: 0.0
cutmix_minmax:
  desc: null
  value: null
mixup_prob:
  desc: null
  value: 1.0
mixup_switch_prob:
  desc: null
  value: 0.5
mixup_mode:
  desc: null
  value: batch
model_ema:
  desc: null
  value: false
model_ema_decay:
  desc: null
  value: 0.9998
seed:
  desc: null
  value: 42
log_interval:
  desc: null
  value: 50
workers:
  desc: null
  value: 8
experiment:
  desc: null
  value: DIST_custom
slurm:
  desc: null
  value: false
local_rank:
  desc: null
  value: 0
dist_port:
  desc: null
  value: '12345'
kd:
  desc: null
  value: dist+
teacher_model:
  desc: null
  value: tv_resnet34
teacher_pretrained:
  desc: null
  value: true
teacher_ckpt:
  desc: null
  value: ''
kd_loss_weight:
  desc: null
  value: 2.0
ori_loss_weight:
  desc: null
  value: 1.0
teacher_module:
  desc: null
  value: ''
student_module:
  desc: null
  value: ''
dbb:
  desc: null
  value: false
dyrep:
  desc: null
  value: false
dyrep_adjust_interval:
  desc: null
  value: 10
dyrep_max_adjust_epochs:
  desc: null
  value: 100
dyrep_recal_bn_iters:
  desc: null
  value: 20
dyrep_recal_bn_every_epoch:
  desc: null
  value: false
edgenn_config:
  desc: null
  value: ''
opt_betas:
  desc: null
  value: null
exp_dir:
  desc: null
  value: experiments/DIST_custom
distributed:
  desc: null
  value: true
device:
  desc: null
  value: cuda:0
world_size:
  desc: null
  value: 1
rank:
  desc: null
  value: 0
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1720762027
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.10.14
      5: 0.17.4
      8:
      - 5
      13: linux-x86_64
